name: Node CI
on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
      - run: npm install -g npm@latest
      - run: npm install -D webpack-cli -y
      - run: npm test
      - run: npm run build